### ISSUE TITLE
Unable to find quasar binary

### ISSUE THREAD

**Issue by DanielAlk** [scakemyer/plugin.video.quasar#169]
Since v0.9.12 it shows "Unable to find quasar binary" error message when kodi starts up.
When I try to access the add-on it asks me to restart kodi.

I'm using openelec 5.0.8 on a raspberry pi 2, kodi version 14.2 - helix

i've checked for the binary at ~/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_arm/
and it's there as it should be.

Thanks for all the good work!

**Comment by DanielAlk** [comment]
copied the linux_arm directory to ~/.kodi/addons/plugin.video.quasar/resources/bin/ and now it's working..

**Comment by penzinho** [comment]
Same problem on mxiii box running openelec (kodi 15.2), your solution worked

**Comment by tobiasvandriessel** [comment]
Same problem as OP, fix not yet tried. RP2 with openelec 6.0.1.

**Comment by scakemyer** [comment]
Copying the quasar binary manually might cause future permissions problems, requiring you to go through the same procedure for every subsequent update. I know a lot of folks reported this problem, here (#160) and on the forum, but the releases are fine and the code that checks for the binary and moves it into place hasn't changed, so you obviously all got a bad update from a third party repository. Please try reinstalling manually from an official [release](https://github.com/scakemyer/plugin.video.quasar/releases), and if it still doesn't work, provide the logs, since no one here, in the other issue or on the forum did regarding this issue.

**Comment by palula** [comment]
Just tried three steps:
1) renamed the linux_arm directory inside _~/.kodi/addons/plugin.video.quasar/resources/bin/_ to linux_arm_original and created a symbolic link for the _~/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_arm/_ directory inside the _~/.kodi/addons/plugin.video.quasar/resources/bin/_
--- reset everything to original state ---

2) copied files just like @DanielAlk said;
--- reset everything to ooriginal state ---

3) noticed that the original quasar binary file inside the ~/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_arm/ directory differed permissions in comparison to the binary file existing in ~/.kodi/addons/plugin.video.quasar/resources/bin/

Applied same permissions and the problem is still happening.

All log lines relating to __quasar__ (grep quasar ~/.kodi/temp/kodi.log) have been pastebinned [here](http://pastebin.com/fTKXcYjw).

**Comment by palula** [comment]
Sorry about the previous post... Just updated using the  [linux_armv7 package](https://github.com/scakemyer/plugin.video.quasar/releases/download/v0.9.25/plugin.video.quasar-0.9.25.linux_armv7.zip) and everything is working smoothly.

Quasar rocks hard, @scakemyer!

**Comment by NikolajChristensen** [comment]
I still get this after everytime the plugin auto updates. Rpi2. A manual install fixes this every time, but at the next auto update it's back and requires a manual update again. Maybe related to the v7 switch over an old install.

**Comment by palula** [comment]
Well I did this from 0.9.28 to 0.9.29 and am already aware that'll have to be done for the [0.9.30](https://github.com/scakemyer/plugin.video.quasar/releases/download/v0.9.30/plugin.video.quasar-0.9.30.linux_armv7.zip).
Am doing it later tonight. \o/

Just:
1) remove all dependent plug-ins (such as providers);
2) remove Quasar;
3) SCP the new version into RPI2 and install it;
4) Install providers.

Takes about 4 minutes, dude.

**Comment by scakemyer** [comment]
Auto-update is working fine on rpi3, if it's not on rpi2, please provide logs and I'll look into it.

**Comment by NikolajChristensen** [comment]
Seems to work with the latest update. Not sure if anything was done specifically?

**Comment by palula** [comment]
Worked with me too.

**Comment by lfrKain** [comment]
Tried with latest version v0.9.33 in rpi3 with openelec with no luck.
I have tested with plugin.video.quasar-0.9.33.linux_arm.zip and plugin.video.quasar-0.9.33.linux_arm64.zip. Also services check are enabled.
Any idea?

**Comment by JMavs** [comment]
I hoy the same problem... If I try it with the provider DivxTotal it works great but if I add EñiteTorrent it doesn't work...

I only see that it works with KickAss and Divxtotal (I'm not English so for me it's not confortable)

**Comment by m4xc4v413r4** [comment]
Logs people, logs....

And @JMavs, no talk about providers here, there are no providers made here and there is no support for them here either.

**Comment by lfrKain** [comment]
I was using wrong package, the right one for the raspberry pi 3 is plugin.video.quasar-0.9.33.linux_armv7.zip. The problem is solved now.

**Comment by ychek** [comment]
Same problem Got: "Unable to find quasar binary" 
On the tvOS 9.1 (Un-Jailbroken) with Kodi 17.0-ALPHA1:
I tried to install all of these releases: 

- plugin.video.quasar-0.9.33.darwin_x64.zip
- plugin.video.quasar-0.9.33.linux_arm.zip
- plugin.video.quasar-0.9.33.linux_arm64.zip
- plugin.video.quasar-0.9.33.linux_armv7.zip
- plugin.video.quasar-0.9.33.linux_x64.zip

@scakemyer Maybe it will work with an other Kodi version?

**Comment by pakerole** [comment]
Hi all, 

I'm facing same issue. Using Kodibuntu and downloaded the official Quasar from the website mentioned by @scakemyer Linux_x86. After reboot, similar error prompted - " Unable to find Quasar binary". 

Please help. My Kodi.log pastebin url after reboot --> [http://paste.ubuntu.com/21268421/](url)

**Comment by kfir2203** [comment]
[Screenshot_2016-10-18-18-23-22.png.zip](https://github.com/scakemyer/plugin.video.quasar/files/536722/Screenshot_2016-10-18-18-23-22.png.zip)
I have the same issue.
I'm using minix Z64 so I've installed the latest quasar (from the official site) in the x64 version and it still can't find the bin file... and I've found the reason why.
In the log file it shows that it searches the bin file in 'android x86' folder instead of 'android x64' where the file is placed.
I've added the log file as proof.

**Comment by kfir2203** [comment]
And in response to that, I tried to create a folder named 'android_x86' and copied the binary to it... it helped a bit, in the log it seems to start progressing but then it failed on another problem.
log file added.
[Screenshot_2016-10-18-18-53-09.png.zip](https://github.com/scakemyer/plugin.video.quasar/files/536768/Screenshot_2016-10-18-18-53-09.png.zip)
