### ISSUE TITLE
Duplicate handling during library integration

### ISSUE THREAD

**Issue by Magic815** [scakemyer/plugin.video.quasar#32]
With all the hopefully upcoming various ways to integrate Quasar streams into Kodi's main Movie/TV Show libraries, it would be great to add in some capability on duplicate handling.

My thinking is there could be a setting that was something like "Integration: Ignore Duplicates?" that was defaulted to 'On.'

That way, when it's on, and I try to integrate the movie 'The Prestige' (whether it's from a Trakt list, or because I used the context menu to integrate it after searching it in Quasar or through another integration method), if I already have a physical local copy of 'The Prestige' in my library, then it would ignore the integration of that .strm file and not add it in.

But then if for some reason a user would want to allow duplicates, they could turn the setting off and then they would have two instances of 'The Prestige' in their library (using the above example).

**Comment by i96751414** [comment]
Although I think this is a good idea, this will be an hard thing to do, because it relies on the scrapper you are currently using...

**Comment by mancuniancol** [comment]
@i96751414, I don't know if it is the same, but I have some code in my viewer for check if the movie/show is already added in the local library

[code]
#  Search if a video is already in Kodi Database
def existInKodiLibrary(id, season="1", episode="1"):
    import json

    result = False
    if 'tt' in id:
        # Movies
        query = {
            'jsonrpc': '2.0',
            'id': 0,
            'method': 'VideoLibrary.GetMovies',
            'params': {
                'properties': ['imdbnumber', 'file']
            }
        }
        response = json.loads(xbmc.executeJSONRPC(json.dumps(query)))
        movieDict = dict(
            (movie['imdbnumber'], movie['file'])
            for movie in response.get('result', {}).get('movies', [])
        )
        if movieDict.has_key(id):
            result = True
    else:
        # TV Shows
        query = {
            'jsonrpc': '2.0',
            'id': 0,
            'method': 'VideoLibrary.GetTVShows',
            'params': {
                'properties': ['imdbnumber', 'file', 'season', 'episode']
            }
        }
        response = json.loads(xbmc.executeJSONRPC(json.dumps(query)))
        showDict = dict(
            (show['imdbnumber'] + "-" + str(show['season']) + "-" + str(show['episode']), show['file'])
            for show in response.get('result', {}).get('tvshows', [])
        )
        if showDict.has_key(id + "-" + str(season) + "-" + str(episode)):
            result = True
    return result
[/code]

The way to use it is with IMDB ID for movies and TVDB ID, season and episode for TV shows;

[code]
existInKodiLibrary("TT000000")  # it will check for that movie

existInKodiLibrary("0000", 1, 1)  # it will check for tv show.

[/code]

I wanted to add to the code, but it think that part is in golang :p

**Comment by i96751414** [comment]
Right, I had the same idea, basically using IMDBID and TVDBID should work fine. But what if the user is using other scrapper? That's what i was trying to say

**Comment by i96751414** [comment]
Anyway, hopefully I will start working on this next week

**Comment by mancuniancol** [comment]
It doesn't matter which scrapper, because it is kodi database which has all the info at the end.

**Comment by i96751414** [comment]
I was talking about kodi's scrappers... But I hope you're right..

**Comment by mancuniancol** [comment]
With that code, I didn't have any problems with the user preference scraper

**Comment by scakemyer** [comment]
@i96751414 Any updates on this? Sorry I had to make changes to `api/library.go` with the switch to TMDB, hope I didn't create conflicts if you were working on this meanwhile.

**Comment by drake0101** [comment]
+1 for duplicates handling.
In my case its tv shows. For example: I already have season 1 on my hdd (and in Kodi's library). The Show has been renewed and now there is a second season available via Quasar. It would be awesome if I add to library the whole TV show in Quasar, but it would only add missing episodes (in this case episodes from season 2).

**Comment by kingdingaling83** [comment]
did this ever get added as a feature?

**Comment by scakemyer** [comment]
Not yet, still planned for v1.0

**Comment by kingdingaling83** [comment]
thank you so much! 
i cannot wait... loving your hard work!

**Comment by kingdingaling83** [comment]
i'm not sure if i'm missing something but i updated to the latest Quasar to test this feature.

- i have seasons 1-4 of Bobs Burgers locally downloaded

1. i chose add to library Bobs Burgers from Trakt inside quasar

2. Quasar added duplicates of episodes i already had locally 

i tried with the setting 'ignore duplicates' off and on

**Comment by scakemyer** [comment]
As @i96751414 mentioned last year, local library IDs depend on the scrapper being used. Movies seem to reliably have their IMDB id set, but shows look like they get whatever ID scrappers give them. Since Quasar is using TMDB IDs for both, I've implemented the feature using those until I find a better solution, probably a setting to specify which scrapper IDs it should use, and should probably default to TVDB also.

**Comment by kingdingaling83** [comment]
ok i'll give that a go

**Comment by scakemyer** [comment]
@kingdingaling83 Releasing v0.9.42 shortly with the setting for which scraper IDs you're using (TVDB, TMDB or Trakt)

**Comment by kingdingaling83** [comment]
Trackt would be ideal as i have different folders using different scrapers so i'll try this tonight

**Comment by kingdingaling83** [comment]
I've just tested using trakt as the scraper.
still getting duplicates.

i checked trakt and i only have 42 episodes out of 114.

duplicates appear :(

**Comment by scakemyer** [comment]
The setting basically just tells Quasar what type of IDs it should expect for shows in your library. If you have different scrapers/IDs there's obviously duplicates it will miss. It's not telling Quasar which scraper to use, it's telling it which one *you* are using for your library.
