### ISSUE TITLE
Streams never start

### ISSUE THREAD

**Issue by DuzAwe** [scakemyer/plugin.video.quasar#687]
## Expected Behavior
Stream to start after selected and one if found

## Current Behavior
Stream never starts, just sits at 0%, eventually will get a file failed to play notice but the stream starting box never goes away.

## Possible Solution
Things were working before the most recent update. I have checked internet and other such possibilities connected to the pi, all of this seems fine.

## Log
https://goo.gl/photos/mWmYbBouEvor76Do7
https://paste.ubuntu.com/23904038

## Context
Currently unable to 'stream' anything but I can play all local files and youtube app. 

## Your Environment

* Version used: Most up to date
* Environment name and version Kodi 15
* Operating System and version: Raspbian Jessie
* Link to Kodi debug log:
https://paste.ubuntu.com/23904038

**Comment by scakemyer** [comment]
Already fixed in 0.9.63, so not the most up to date. Also note that Kodi 15 is on its way out.

But looking at the logs, you have some networking issues unrelated to Quasar:
```
ERRO  tmdb         ▶ tmdbCheck        [0mGet https://api.themoviedb.org/3/movie/550?api_key=ae4bd1b6fce2a5648671bfc171d15ba4: dial tcp 54.243.147.233:443: getsockopt: no route to host
...
ERRO  libtorrent   ▶ logAlerts        [0mportmap_error_alert: could not map port using UPnP: Action Failed
...
WARN  repository   ▶ GetAddonFiles    [0mUnable to find a last tag, using master.
WARN  repository   ▶ getAddons        [0mUnable to retrieve the addon.xml file, checking backup repository...
...
ERRO  tmdb         ▶ 1                [0mGet https://api.themoviedb.org/3/discover/movie?api_key=8cf43ad9c085135b9479ad5cf6bbcbda&language=en&page=3&primary_release_date.lte=2017-01-31&sort_by=popularity.desc: dial tcp 54.243.147.233:443: getsockopt: no route to host
```
And it goes on and on... Check your Kodi settings or whatever network setup you have before blaming Quasar and the "last update"...

**Comment by DuzAwe** [comment]
Thanks for working so fast, I know how much of a drag it can be to have people at you all the time while do this for free. You must of literally just pushed the update as I was trouble shooting. 
I'd plugged the pi directly into my router without any bridge and was still unable to so I had just assumed. I also made a mistake Im on Kodi 16, 15 is the one in the official repo.

Thank you again.

**Comment by scakemyer** [comment]
It's all good, thanks for properly filing the issue in the first place.
