### ISSUE TITLE
Quasar not working (Android,Kodi 18, IOError (22, Invalid Argument )

### ISSUE THREAD

**Issue by niamod** [scakemyer/plugin.video.quasar#925]
## Expected Behavior
Quasar to run when Kodi starts
## Current Behavior
When Kodi starts the above error appear, It was working few days ago, no updates, no new addon installs, Quasar cannot be de-installed because when try to enter into quasar kodi hangs.  
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
Quasar 0.9.78
* Environment name and version:
Kodi 18 Lea - ALPHA1 - works perfectly with Krypton 17.6
* Operating System and version:

* Link to Kodi debug log:
https://pastebin.com/EfiFGi1B

**Comment by tomtomclub** [comment]
i donte update but try dis 

https://github.com/elgatito/plugin.video.elementum/releases

**Comment by deleder** [comment]
Will there ever be an update so that Kodi 18 works? I've tried Elementum but it is very slow on Android compared to Quasar (save to disk). I have a 32 GB disk, and watching 20 GB 2160p HDR MKV's was working fine with Quasar. 

I need DASH 2160p to work, and only Kodi 18 supports it :/

**Comment by embedded1** [comment]
Any update?
Kodi was auto updated to version 18 and now quasar doesn't load.
Any fix available?

**Comment by logon84** [comment]
Fixed here for Android arm:
https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789

**Comment by burekas7** [comment]
@deleder 
Try to use the new version of Elementum 0.1.x (0.1.14 has bugs so use 0.1.13 for now)
It's using the same torrent engine that Quasar is using, and the speed is much better with this version.
(I still don't know if it's compatible with 18, I'm still using 17.6 , but I think it is)

**Comment by scakemyer** [comment]
Maintenance release coming soon

**Comment by Cereal-Killa** [comment]
> Fixed here for Android arm:
> https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789

Tried that zip on my MiBox, it installs 0.9.788 and IO Error still happens.

**Comment by logon84** [comment]
> > Fixed here for Android arm:
> > https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789
> 
> Tried that zip on my MiBox, it installs 0.9.788 and IO Error still happens.

Is 'fp.seek(-40, os.SEEK_END) ' what is causing your IO error (like log on topic)?

**Comment by kakaty76** [comment]
Alguém já conseguiu roda o guasar no Kodi 18

**Comment by an0nimo** [comment]
> Fixed here for Android arm:
> https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789

**I am using the Leia v18.3 version on Android and didn't work**. I saw that ELEMENTUM addon had the same issue and was solved:
[https://github.com/elgatito/plugin.video.elementum/issues/66](url)
I tried replace the daemon.py file of the quasar to elementum, obviously changing all "elementum" words to "quasar", but didn't work.
_**Error log:**_
2019-08-19 01:42:52.508 T:30993  NOTICE: [plugin.video.quasar] quasard: starting quasard
2019-08-19 01:42:52.517 T:30993  NOTICE: [plugin.video.quasar] Kodi's JSON-RPC service is available, starting up...
2019-08-19 01:42:52.517 T:30993  NOTICE: [plugin.video.quasar] Detected binary folder: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
2019-08-19 01:42:52.521 T:30993  NOTICE: [plugin.video.quasar] Using binary folder: /storage/emulated/legacy/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
2019-08-19 01:42:52.807 T:30993   ERROR: [plugin.video.quasar] Traceback (most recent call last):
2019-08-19 01:42:52.808 T:30993   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 214, in quasard_thread
2019-08-19 01:42:52.819 T:30993   ERROR: [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
2019-08-19 01:42:52.819 T:30993   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in start_quasard
2019-08-19 01:42:52.820 T:30993   ERROR: [plugin.video.quasar]     quasar_dir, quasar_binary = get_quasar_binary()
2019-08-19 01:42:52.820 T:30993   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 64, in get_quasar_binary
2019-08-19 01:42:52.821 T:30993   ERROR: [plugin.video.quasar]     if not os.path.exists(dest_binary_path) or get_quasard_checksum(dest_binary_path) != get_quasard_checksum(binary_path):
2019-08-19 01:42:52.822 T:30993   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 28, in get_quasard_checksum
2019-08-19 01:42:52.822 T:30993   ERROR: [plugin.video.quasar]     fp.seek(-40, os.SEEK_END)  # we put a sha1 there
2019-08-19 01:42:52.822 T:30993   ERROR: [plugin.video.quasar] IOError: [Errno 22] Invalid argument
2019-08-19 01:42:52.823 T:30993   ERROR: [plugin.video.quasar]

**Comment by caesar96** [comment]
> > Fixed here for Android arm:
> > https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789
> 
> **I am using the Leia v18.3 version on Android and didn't work**. I saw that ELEMENTUM addon had the same issue and was solved:
> [https://github.com/elgatito/plugin.video.elementum/issues/66](url)
> I tried replace the daemon.py file of the quasar to elementum, obviously changing all "elementum" words to "quasar", but didn't work.
> _**Error log:**_
> 2019-08-19 01:42:52.508 T:30993 NOTICE: [plugin.video.quasar] quasard: starting quasard
> 2019-08-19 01:42:52.517 T:30993 NOTICE: [plugin.video.quasar] Kodi's JSON-RPC service is available, starting up...
> 2019-08-19 01:42:52.517 T:30993 NOTICE: [plugin.video.quasar] Detected binary folder: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
> 2019-08-19 01:42:52.521 T:30993 NOTICE: [plugin.video.quasar] Using binary folder: /storage/emulated/legacy/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
> 2019-08-19 01:42:52.807 T:30993 ERROR: [plugin.video.quasar] Traceback (most recent call last):
> 2019-08-19 01:42:52.808 T:30993 ERROR: [plugin.video.quasar] File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 214, in quasard_thread
> 2019-08-19 01:42:52.819 T:30993 ERROR: [plugin.video.quasar] proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> 2019-08-19 01:42:52.819 T:30993 ERROR: [plugin.video.quasar] File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in start_quasard
> 2019-08-19 01:42:52.820 T:30993 ERROR: [plugin.video.quasar] quasar_dir, quasar_binary = get_quasar_binary()
> 2019-08-19 01:42:52.820 T:30993 ERROR: [plugin.video.quasar] File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 64, in get_quasar_binary
> 2019-08-19 01:42:52.821 T:30993 ERROR: [plugin.video.quasar] if not os.path.exists(dest_binary_path) or get_quasard_checksum(dest_binary_path) != get_quasard_checksum(binary_path):
> 2019-08-19 01:42:52.822 T:30993 ERROR: [plugin.video.quasar] File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 28, in get_quasard_checksum
> 2019-08-19 01:42:52.822 T:30993 ERROR: [plugin.video.quasar] fp.seek(-40, os.SEEK_END) # we put a sha1 there
> 2019-08-19 01:42:52.822 T:30993 ERROR: [plugin.video.quasar] IOError: [Errno 22] Invalid argument
> 2019-08-19 01:42:52.823 T:30993 ERROR: [plugin.video.quasar]

Same issue. Don't know what to do to have Quasar working on Android TV Arm

**Comment by an0nimo** [comment]
> Fixed here for Android arm:
> https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789

@logon84 
I appreciate your great intention to help but now the Quasar stop and restart 3 times until to be canceled.
Worked fine with Kodi 17.5.
My Android is Lollipop 5.1.1 (api 22) armv8

**Comment by asoryeslew** [comment]
> Fixed here for Android arm:
> https://github.com/logon84/plugin.video.quasar/releases/tag/v0.9.789

Works here.

**Comment by ddogishere** [comment]
Hello any fix/suggestion for this, i love using Quasar on Android 9 but want to update to android 10, Thx

**Comment by kakaty76** [comment]
Usa o elemetum

Enviado do Outlook Mobile<https://aka.ms/blhgte>
________________________________
